//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSeat
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> SeatId { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
