//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public int CinemaId { get; set; }
        public System.DateTime WeekDay { get; set; }
        public System.DateTime TimeOfStart { get; set; }
        public System.DateTime TimeOfEnd { get; set; }
    
        public virtual Cinema Cinema { get; set; }
    }
}
